site_name: My Conference Radar
theme:
  name: material

plugins:
  - search

nav:
  - Home: index.md
  - Conferences: conferences.md

extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - https://cdn.datatables.net/2.0.8/js/dataTables.min.js
  - assets/js/conferences.js

extra_css:
  - https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.min.css
  - assets/css/custom.css